// @ts-check
/**
 * The audit manifest's file inventory must match the bundle it describes
 * (contract §27 "the audit package").
 *
 * NOT a reproduced defect — stated plainly. I checked the revision-3 manifest
 * against the revision-3 bundle before writing this file:
 *
 *   $ # listed paths vs. walked bundle, .git and node_modules excluded
 *   shipped but NOT listed: 0
 *   listed but NOT shipped: 0
 *
 * The revision-3 inventory was accurate. This test exists because that accuracy
 * was maintained by hand and revision 4 adds eleven files; a manifest that omits
 * a shipped file — or names one that is not shipped — is a false statement about
 * what the auditor received, which is what §27 exists to prevent. It is
 * preventive, and it will not fail against revision 3.
 *
 * The inventory is now generated by `tools/writeManifestPaths.mjs`; this test
 * runs that tool's `--check` logic in the build-blocking suite.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { bundledPaths, renderInventory, spliceInventory } from "../tools/writeManifestPaths.mjs";

const ROOT = resolve(join(dirname(fileURLToPath(import.meta.url)), ".."));
const MANIFEST = readFileSync(join(ROOT, "AUDIT_PACKAGE_MANIFEST.md"), "utf8");

test("§27 — the manifest's path inventory is current", () => {
  const paths = bundledPaths();
  const expected = spliceInventory(MANIFEST, renderInventory(paths));
  assert.equal(
    MANIFEST,
    expected,
    "AUDIT_PACKAGE_MANIFEST.md path inventory is stale — run `node tools/writeManifestPaths.mjs`"
  );
});

test("§27 — every shipped file is listed, and every listed file is shipped", () => {
  const paths = bundledPaths();
  assert.ok(paths.length > 60, `expected a substantial bundle, found ${paths.length} files`);

  // Listed set == shipped set, compared as sets so the failure names the diff.
  const block = MANIFEST.slice(
    MANIFEST.indexOf("<!-- BEGIN GENERATED PATH INVENTORY -->"),
    MANIFEST.indexOf("<!-- END GENERATED PATH INVENTORY -->")
  );
  const listed = [...block.matchAll(/^- `([^`]+)`$/gm)].map((m) => m[1]);
  const missing = paths.filter((p) => !listed.includes(p));
  const phantom = listed.filter((p) => !paths.includes(p));
  assert.deepEqual(missing, [], `shipped but not listed in the manifest: ${missing.join(", ")}`);
  assert.deepEqual(phantom, [], `listed in the manifest but not shipped: ${phantom.join(", ")}`);
  assert.match(block, new RegExp(`\\*\\*${paths.length} files\\.\\*\\*`), "the stated count must match");
});

test("§27 — the revision-4 additions are actually in the bundle", () => {
  const paths = bundledPaths();
  const required = [
    // production
    "src/config/milestoneStatus.js",
    "src/fixtures/edgeOnlyWorlds.js",
    // tooling required for reproducible evidence
    "tools/measureDesktop.mjs",
    "tools/writeFinalReport.mjs",
    "tools/writeManifestPaths.mjs",
    // the dependency declaration and lockfile the desktop measurement needs
    "package.json",
    "package-lock.json",
    // revision-4 regression tests
    "test/observer-transaction-integrity.test.js",
    "test/focal-lineage-integrity.test.js",
    "test/canvas-jitter-membership.test.js",
    "test/desktop-measurement-reproducibility.test.js",
    "test/traversal-label-integrity.test.js",
    "test/report-integrity.test.js",
    "test/manifest-inventory.test.js",
    // documents
    "REVISION_4_REPAIR_RECORD.md",
    "STRUCTURAL_AUDIT_REPAIR_RECORD.md",
    "CHARACTERIZATION_PLAN.md",
    // evidence
    "audit/meaningful-trait-gate.json",
    "audit/desktop-measurements.json",
    "audit/edge-only-traversal-results.json",
  ];
  for (const rel of required) {
    assert.ok(paths.includes(rel), `${rel} must be in the bundle`);
  }
});

test("§27 — only the permitted categories are excluded", () => {
  const paths = bundledPaths();
  // No excluded category may leak INTO the bundle listing.
  for (const p of paths) {
    assert.ok(!p.startsWith(".git/"), `${p}: version-control metadata must be excluded`);
    assert.ok(!p.startsWith("node_modules/"), `${p}: node_modules must be excluded`);
    assert.ok(!/(^|\/)\.DS_Store$/.test(p), `${p}: OS metadata must be excluded`);
    assert.ok(!p.endsWith(".swp") && !p.endsWith("~"), `${p}: editor temporaries must be excluded`);
  }
  // Nothing else may be dropped: source, tests, tools, evidence, fixtures and the
  // quarantined references must all be present.
  for (const dir of ["src/", "test/", "tools/", "audit/", "fixtures/", "reference/"]) {
    assert.ok(paths.some((p) => p.startsWith(dir)), `${dir} must be represented in the bundle`);
  }
  assert.equal(
    paths.filter((p) => p.startsWith("reference/")).length,
    3,
    "all three quarantined Python references must ship"
  );
});
