// @ts-check
/**
 * FINAL_REPORT.md must agree with the raw evidence it claims to summarize
 * (contract §26 status artifacts, §27 audit evidence, §28 completion law).
 *
 * Revision-4 repair. Revisions 1-3 hand-maintained the report and it drifted.
 * Reproduced against the revision-3 bundle:
 *
 *   $ grep -n "Config hash" FINAL_REPORT.md
 *   54:- Config hash: `edb81695973b81ab8f87f7ef9dde9d8c5b3d4c7dfbeb45f385547edd86ee86de`
 *
 *     A DUPLICATED build-identity block (lines 51-57 repeated lines 35-38) that
 *     published `edb81695…` as "Config hash", while line 141 of the SAME report
 *     labelled that hash "the tuning config only" and named
 *     `modelDefinitionHash` as the complete one. The report contradicted itself
 *     about which hash identifies the model.
 *
 *   $ grep -o "119 tests" FINAL_REPORT.md | head -1 ; grep "^# tests" audit/test-results.txt
 *   119 tests
 *   # tests 172
 *
 *     The gate table claimed "119 tests … 119/119" while the raw TAP summary in
 *     the same bundle reported 172.
 *
 *   $ grep -n "Memory across a 180-generation run" -A1 FINAL_REPORT.md
 *     A browser `performance.memory` delta published as memory-growth evidence,
 *     from a channel that was never probed for resolution.
 *
 * The report is now GENERATED by `tools/writeFinalReport.mjs`. These tests make
 * drift a build failure: every assertion compares the committed report against
 * the raw evidence, and several re-derive the number independently rather than
 * trusting either file.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { renderFinalReport, parseTap, selfAuditScans } from "../tools/writeFinalReport.mjs";
import { MILESTONE_STATUS, HASH_LABELS } from "../src/config/milestoneStatus.js";
import { exactProbabilityGate } from "../tools/runFixture.mjs";
import { buildMeaningfulTraitGateEvidence } from "../tools/writeAuditEvidence.mjs";
import { currentModelConfig } from "../src/config/modelConfig.js";
import { ZONES } from "../src/config/zones.js";

const ROOT = resolve(join(dirname(fileURLToPath(import.meta.url)), ".."));
const read = (p) => readFileSync(join(ROOT, p), "utf8");
const readJson = (p) => JSON.parse(read(p));

const REPORT = read("FINAL_REPORT.md");
const TAP = parseTap(read("audit/test-results.txt"));
const FIXTURE = readJson("audit/fixture-results.json");
const CHAR = readJson("audit/characterization-results.json");
const OBS = readJson("audit/observer-invariance-hashes.json");
const REFS = readJson("audit/reference-file-hashes.json");

test("§26 — the committed report is exactly what the generator produces", () => {
  // The single strongest check: if anyone hand-edits the report, this fails.
  assert.equal(
    REPORT,
    renderFinalReport(),
    "FINAL_REPORT.md differs from `node tools/writeFinalReport.mjs` output — regenerate it " +
    "with `npm run report:final` instead of editing it by hand"
  );
});

test("§20 — the report's suite counts equal the raw TAP summary", () => {
  assert.ok(TAP.tests !== null, "the raw TAP summary must be parseable");
  assert.ok(TAP.pass !== null && TAP.fail !== null);

  // Every count must appear in the report...
  for (const [label, value] of [["tests", TAP.tests], ["pass", TAP.pass], ["fail", TAP.fail]]) {
    assert.match(
      REPORT,
      new RegExp(`\\| ${label} \\| ${value} \\|`),
      `the report must print the raw ${label} count ${value}`
    );
  }
  // ...and the gate-table summary must state the SAME outcome, in whichever form
  // applies. A green run reads "N/N, 0 failures"; a failing run must say FAIL with
  // the real numbers rather than quietly printing a pass shape.
  if (TAP.fail === 0) {
    const green = [...REPORT.matchAll(/(\d+)\s*\/\s*(\d+), 0 failures/g)].map((m) => [Number(m[1]), Number(m[2])]);
    assert.ok(green.length > 0, "a green run must state the pass/total summary");
    for (const [p, t] of green) {
      assert.equal(t, TAP.tests, `the report claims ${t} tests but the runner reported ${TAP.tests}`);
      assert.equal(p, TAP.pass, `the report claims ${p} passing but the runner reported ${TAP.pass}`);
    }
    assert.ok(
      !/\*\*FAIL\*\* — \d+ of \d+ failing/.test(REPORT),
      "a green run must not print a failing summary"
    );
  } else {
    const red = [...REPORT.matchAll(/\*\*FAIL\*\* — (\d+) of (\d+) failing/g)].map((m) => [Number(m[1]), Number(m[2])]);
    assert.ok(red.length > 0, "a failing run must be reported as FAIL, not hidden");
    for (const [f, t] of red) {
      assert.equal(f, TAP.fail, `the report claims ${f} failures but the runner reported ${TAP.fail}`);
      assert.equal(t, TAP.tests, `the report claims ${t} tests but the runner reported ${TAP.tests}`);
    }
  }

  // Wall-clock duration must NOT be reproduced: it differs on every run, so
  // printing it would make this comparison unsatisfiable by construction.
  assert.ok(
    !/^\| duration \|/m.test(REPORT),
    "the report must not print the run duration — it is nondeterministic and would " +
    "make the report and the results file permanently disagree"
  );
  // No stale count from an earlier revision may be ASSERTED. Quoting one inside an
  // explicit withdrawal is required, not forbidden — §9b names the revision-3
  // "119 tests … 119/119" claim precisely so a reader cannot carry it forward.
  for (const stale of [119, 122, 148, 172]) {
    if (stale === TAP.tests) continue;
    const pattern = new RegExp(`${stale}\\s*/\\s*${stale}`);
    const lines = REPORT.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (!pattern.test(lines[i])) continue;
      const context = lines.slice(Math.max(0, i - 6), i + 4).join(" ");
      assert.match(
        context,
        /[Ww]ithdrawn|[Rr]evision[- ][123]|stale|retired/,
        `the report asserts the stale suite count ${stale}/${stale} outside a withdrawal:\n  ${lines[i].trim()}`
      );
    }
  }
});

test("§9/§18 — modelDefinitionHash is the principal identity and the subset hash is labelled nonauthoritative", () => {
  assert.ok(
    REPORT.includes(`\`${HASH_LABELS.authoritative}\`** (authoritative)`),
    "the complete-model hash must be presented as authoritative"
  );
  assert.ok(
    REPORT.includes(`\`${HASH_LABELS.nonauthoritative}\` (**NONAUTHORITATIVE**)`),
    "the tuning-only subset hash must be explicitly labelled nonauthoritative"
  );
  assert.ok(REPORT.includes(CHAR.modelDefinitionHash), "the authoritative hash value must be printed");
  assert.ok(REPORT.includes(CHAR.tuningConfigHash), "the subset hash value must be printed, labelled");

  // The subset hash must never be presented as "the" config hash again.
  assert.ok(
    !/^\s*[-|]\s*Config hash:/m.test(REPORT),
    'no line may publish a bare "Config hash:" — the report distinguishes the two hashes'
  );
  // Exactly one build-identity block. Revision 3 had two.
  const identityBlocks = [...REPORT.matchAll(/### Build identity/g)].length;
  assert.equal(identityBlocks, 1, "the report must contain exactly one build-identity block");
  const configLines = [...REPORT.matchAll(/^\| Configuration \| /gm)].length;
  assert.equal(configLines, 1, "the configuration must be stated exactly once");

  // Evidence files must agree with each other on both hashes.
  assert.equal(FIXTURE.modelDefinitionHash, CHAR.modelDefinitionHash, "evidence files disagree on the model hash");
  assert.equal(FIXTURE.tuningConfigHash, CHAR.tuningConfigHash, "evidence files disagree on the subset hash");
  assert.notEqual(CHAR.modelDefinitionHash, CHAR.tuningConfigHash, "the two hashes must be distinguishable");
});

test("§26 — the report's status comes from the single source of truth", () => {
  assert.ok(REPORT.includes(MILESTONE_STATUS.status), "the report must state the canonical status");
  assert.ok(REPORT.includes(MILESTONE_STATUS.processWaiver));
  assert.ok(REPORT.includes(MILESTONE_STATUS.ipadTest));
  assert.equal(MILESTONE_STATUS.mayDeclareCompletion, false);
  assert.ok(
    REPORT.includes("**Completion is NOT declared**"),
    "the report must not declare completion while mayDeclareCompletion is false"
  );
  // Forbidden statuses may appear only inside an explicit withdrawal.
  for (const forbidden of MILESTONE_STATUS.forbiddenStatuses) {
    for (const line of REPORT.split("\n")) {
      if (!line.includes(forbidden)) continue;
      assert.match(
        line,
        /withdraw|must not|not reinstated|was false|revision 1|revision 2/i,
        `the report presents ${forbidden} as a current status:\n  ${line.trim()}`
      );
    }
  }
});

test("§19.3/§19.4 — fixture numbers in the report match the evidence AND a fresh computation", () => {
  // The report's §19.4 figures must be the evidence's figures.
  assert.match(REPORT, new RegExp(`\\*\\*${FIXTURE.successCounts.canopy} / ${FIXTURE.gates.seedCount}\\*\\*`));
  assert.match(REPORT, new RegExp(`\\*\\*${FIXTURE.successCounts.shoreline} / ${FIXTURE.gates.seedCount}\\*\\*`));
  assert.ok(REPORT.includes(FIXTURE.medians.canopyLow.toFixed(4)));
  assert.ok(REPORT.includes(FIXTURE.medians.shorelineHigh.toFixed(4)));
  assert.ok(REPORT.includes(String(FIXTURE.focalContributionExtinctionCount)));

  // The §19.3 gate must be present as evidence, not prose, and must reproduce.
  assert.ok(FIXTURE.exactProbabilityGate, "the §19.3 gate must be emitted into the evidence file");
  const fresh = exactProbabilityGate(currentModelConfig);
  for (const k of ["canopyLow", "canopyHigh", "canopyDelta", "shorelineLow", "shorelineHigh", "shorelineDelta"]) {
    assert.equal(
      FIXTURE.exactProbabilityGate[k],
      fresh[k],
      `${k} in the evidence file does not reproduce from the production survival path`
    );
  }
  assert.ok(REPORT.includes(fresh.canopyDelta.toFixed(6)), "the report must print the measured canopy delta");
  assert.ok(REPORT.includes(fresh.shorelineDelta.toFixed(6)), "the report must print the measured shoreline delta");
  assert.equal(fresh.allPass, true);
});

test("§9 — every trait delta in the report reproduces from the production path", () => {
  const evidence = readJson("audit/meaningful-trait-gate.json");
  const fresh = buildMeaningfulTraitGateEvidence();
  assert.equal(evidence.meaningful.length, fresh.meaningful.length);
  for (let i = 0; i < fresh.meaningful.length; i++) {
    const e = evidence.meaningful[i];
    const f = fresh.meaningful[i];
    assert.equal(e.trait, f.trait);
    for (const z of ZONES) {
      assert.equal(e.deltaByZone[z], f.deltaByZone[z], `${e.trait}/${z} does not reproduce`);
      assert.ok(
        REPORT.includes(f.deltaByZone[z].toFixed(6)),
        `the report must print the measured delta for ${f.trait}/${z}`
      );
    }
  }
  for (const n of fresh.neutral) {
    assert.equal(n.maxAbsoluteDelta, 0, `${n.trait} must be exactly neutral`);
  }
  assert.equal(evidence.allMeaningfulPass, true);
  assert.equal(evidence.allNeutralExactlyZero, true);
  assert.equal(evidence.probe.fixtureGenomeMatches, true, "the §9 probe must use the fixture's frozen genome");
});

test("§21.4 — guardrail figures and the named limitation match the raw batch", () => {
  const g = CHAR.guardrails;
  assert.ok(REPORT.includes(g.medianPopulation.toFixed(1)));
  for (let z = 0; z < ZONES.length; z++) {
    assert.ok(
      REPORT.includes(g.medianZoneLoads[z].toFixed(2)),
      `the report must print the measured ${ZONES[z]} median load`
    );
  }
  assert.ok(REPORT.includes(g.medianConcentration.toFixed(4)));
  assert.ok(REPORT.includes(`${(g.extinctionRate * 100).toFixed(2)}%`));
  assert.ok(REPORT.includes(`all ${g.concentrationIncludedSeedCount} non-extinct seeds`));

  // The named limitation must be re-derived from the per-seed records, and must
  // agree with what CHARACTERIZATION.md prints.
  const nonExtinct = CHAR.seeds.filter((s) => !s.extinct);
  const shorelineZeroBin = nonExtinct.filter((s) => s.zoneBinCounts[2] === 0).length;
  assert.ok(shorelineZeroBin > 0, "the limitation must be a real measurement, not a placeholder");
  assert.match(
    REPORT,
    new RegExp(`zero in ${shorelineZeroBin} of ${CHAR.declaredSeedRange.endInclusive} seeds`),
    `the report must state the measured count ${shorelineZeroBin}`
  );
  const characterization = read("CHARACTERIZATION.md");
  assert.ok(
    characterization.includes(`${shorelineZeroBin} of ${nonExtinct.length}`),
    "CHARACTERIZATION.md must state the same count as FINAL_REPORT.md"
  );
  // Medians must agree between the two reports, to the digits both print.
  for (let z = 0; z < ZONES.length; z++) {
    const printed = CHAR.guardrails.medianZoneLoads[z].toFixed(2);
    assert.ok(characterization.includes(printed), `CHARACTERIZATION.md must print ${printed}`);
  }
});

test("§22 — desktop figures in the report match the desktop JSON exactly", () => {
  if (!existsSync(join(ROOT, "audit", "desktop-measurements.json"))) {
    assert.fail("audit/desktop-measurements.json is required evidence");
  }
  const d = readJson("audit/desktop-measurements.json");
  assert.ok(REPORT.includes(d.browser.version), "the report must print the measured browser version");
  assert.ok(REPORT.includes(String(d.normalMode.frameCount)));
  assert.ok(REPORT.includes(String(d.renderStressMode.frameCount)));
  assert.ok(REPORT.includes(d.normalMode.medianFrameTimeMs.toFixed(2)));
  assert.ok(REPORT.includes(d.renderStressMode.p95FrameTimeMs.toFixed(2)));
  assert.ok(REPORT.includes(String(d.normalMode.populationAfterAdvance)));

  // Generation semantics must be stated, and consistent.
  assert.match(
    REPORT,
    new RegExp(`\\*\\*${d.generationSemantics.finalStateGeneration}\\*\\* with \\*\\*${d.normalMode.populationAfterAdvance}\\*\\* living`),
    "the report must tie the population to an explicit final generation"
  );
  // The ambiguous revision-3 field name must not be a live key anywhere. The
  // report is allowed to NAME it while explaining the defect — that mention is
  // the record — so the rule is about use, not about the English text.
  const deskText = read("audit/desktop-measurements.json");
  assert.ok(
    !deskText.includes("populationAfter180Generations"),
    "the ambiguous field name must not appear in the raw desktop evidence"
  );
  const reportLines = REPORT.split("\n");
  for (let i = 0; i < reportLines.length; i++) {
    if (!reportLines[i].includes("populationAfter180Generations")) continue;
    // Judge the surrounding context, not the single line: a withdrawal can put the
    // marker in its section heading or the following sentence.
    const context = reportLines.slice(Math.max(0, i - 6), i + 4).join(" ");
    assert.match(
      context,
      /[Rr]evision[- ]3|ambiguity|retired|[Ww]ithdrawn/,
      `the report mentions populationAfter180Generations without marking it as the revision-3 name:\n  ${reportLines[i].trim()}`
    );
  }

  // Memory: the report must not publish an unverified browser delta as evidence.
  const mem = d.memoryAcrossAdvance;
  assert.ok(REPORT.includes("`node:process.memoryUsage()`"), "the authoritative channel must be named");
  if (!mem.browser.usable) {
    assert.ok(
      REPORT.includes("**The browser heap figure is withdrawn as evidence.**"),
      "an unusable browser memory channel must be withdrawn in the report, not quietly printed"
    );
    // The old style of claim must be gone.
    assert.ok(
      !/Memory across a 180-generation run: [\d,]+ → [\d,]+ bytes/.test(REPORT),
      "the report must not present a browser heap delta as the memory-growth result"
    );
  }
  // The desktop run must not be presented as satisfying the iPad gate.
  assert.equal(d.windowComparison.satisfiesIpadGateWindows, false);
  assert.ok(REPORT.includes("Satisfies the iPad gate's windows: false"));
  assert.ok(REPORT.includes("PENDING_HUMAN_DEVICE_TEST"));
});

test("§21.6 — the report gives the traversal claim to the isolated worlds", () => {
  const edge = readJson("audit/edge-only-traversal-results.json");
  assert.ok(REPORT.includes("**Authoritative evidence: the isolated edge-only worlds only.**"));
  for (const key of ["canopyOnly", "shorelineOnly"]) {
    const e = edge[key];
    assert.ok(
      REPORT.includes(`**${e.seedsReaching} of ${e.ofSeeds}**`),
      `the report must print the measured ${key} count`
    );
  }
  const authIdx = REPORT.indexOf("## 6b. §21.6 adjacency traversal");
  const suppIdx = REPORT.indexOf("### Supporting measure only — mixed-world single-band ancestry (NOT the §21.6 claim)");
  assert.ok(authIdx >= 0 && suppIdx > authIdx, "the supporting measure must follow, and disclaim, the real one");
  const L = CHAR.lifecycle;
  const mixC = L.additionalMixedWorldCanopyAncestryReachesShoreline;
  assert.ok(
    REPORT.includes(`${mixC.seedsReaching} of ${mixC.ofSeeds}`),
    "the mixed-world figure must be the measured one"
  );
});

test("§27 — observer-invariance and reference-file claims match their evidence", () => {
  assert.equal(OBS.allStrategiesByteIdentical, true);
  assert.equal(OBS.mismatches.length, 0);
  assert.ok(
    REPORT.includes(`**${OBS.strategies.length} strategies × ${OBS.generations + 1} generations`),
    "the report must print the measured strategy and generation counts"
  );
  assert.equal(REFS.allUnchanged, true);
  assert.ok(REPORT.includes(`${REFS.allUnchanged} (${REFS.files.length} files)`));
});

test("§27 — the manifest's evidence-file list matches what actually exists", () => {
  const manifest = read("AUDIT_PACKAGE_MANIFEST.md");
  const required = [
    "audit/test-results.txt",
    "audit/fixture-results.json",
    "audit/characterization-results.json",
    "audit/characterization-results-config1.json",
    "audit/observer-invariance-hashes.json",
    "audit/reference-file-hashes.json",
    "audit/edge-only-traversal-results.json",
    "audit/desktop-measurements.json",
    "audit/meaningful-trait-gate.json",
  ];
  for (const rel of required) {
    assert.ok(existsSync(join(ROOT, rel)), `${rel} must exist`);
    assert.ok(manifest.includes(rel), `AUDIT_PACKAGE_MANIFEST.md must list ${rel}`);
  }
  // Every audit file the manifest names must exist — no phantom evidence.
  for (const m of manifest.matchAll(/`(audit\/[A-Za-z0-9._-]+)`/g)) {
    assert.ok(existsSync(join(ROOT, m[1])), `the manifest names ${m[1]}, which does not exist`);
  }
  // Every audit file that exists must be named — no undisclosed evidence.
  // `audit/test-results.txt.partial` is excluded: it exists only while the suite is
  // running and is renamed over the published file on exit (tools/runTests.mjs).
  // Without this exclusion the check failed against the very run executing it,
  // which says nothing about whether the manifest is honest.
  for (const name of readdirSync(join(ROOT, "audit"))) {
    if (name.endsWith(".partial")) continue;
    assert.ok(
      manifest.includes(`audit/${name}`),
      `audit/${name} exists but is not listed in AUDIT_PACKAGE_MANIFEST.md`
    );
  }
});

test("§26 — the report is marked as generated so it is not hand-edited", () => {
  assert.ok(REPORT.startsWith("# LINEAGE Milestone 1 — Final Implementation Report"));
  assert.ok(REPORT.includes("> **GENERATED FILE.**"));
  assert.ok(REPORT.includes("tools/writeFinalReport.mjs"));
  const pkg = readJson("package.json");
  assert.equal(pkg.scripts["report:final"], "node tools/writeFinalReport.mjs");
});

test("§24 Stage G — the self-audit scans are real: they detect a planted violation", () => {
  // A scan that always reports "clean" is worthless. Revision 3 stated these
  // results as prose; revision 4 executes them at report-generation time. This
  // test proves the scanner has teeth, without leaving any violation behind.
  const scan = selfAuditScans();
  assert.deepEqual(scan.unseededRandom, [], "no unseeded randomness may ship");
  assert.deepEqual(scan.observerImports, [], "biology must not import observer or debug modules");
  assert.deepEqual(scan.observerRngRefs, [], "observer modules must not touch the simulation RNG");
  assert.deepEqual(scan.bareImports, [], "src/ must have no runtime dependencies");

  // Plant each violation in turn, confirm the scan reports it, and restore.
  const cases = [
    { file: "src/core/math.js", inject: 'import { zoneBinCounts } from "../observer/currentZoneBins.js";\n', key: "observerImports" },
    { file: "src/core/math.js", inject: 'import x from "some-npm-package";\n', key: "bareImports" },
    { file: "src/observer/currentZoneBins.js", inject: "// touches simRng\n", key: "observerRngRefs" },
    { file: "src/core/math.js", inject: `const r = ${["Math", "random"].join(".")}();\n`, key: "unseededRandom" },
  ];
  for (const c of cases) {
    const path = join(ROOT, c.file);
    const original = readFileSync(path, "utf8");
    try {
      writeFileSync(path, c.inject + original);
      const planted = selfAuditScans();
      assert.ok(
        planted[c.key].length > 0,
        `the ${c.key} scan failed to detect a planted violation in ${c.file}`
      );
      assert.ok(
        planted[c.key].some((entry) => entry.includes(c.file)),
        `the ${c.key} scan did not name ${c.file}`
      );
    } finally {
      writeFileSync(path, original);
    }
  }

  // Everything is clean again — the test left no residue.
  const after = selfAuditScans();
  assert.deepEqual(after, scan, "the test must restore every file it modified");
});
