// @ts-check
/**
 * FINAL_REPORT.md must agree with the raw evidence it claims to summarize
 * (contract §26 status artifacts, §27 audit evidence, §28 completion law).
 *
 * Revision-4 repair. Revisions 1-3 hand-maintained the report and it drifted.
 * Reproduced against the revision-3 bundle:
 *
 *   $ grep -n "Config hash" FINAL_REPORT.md
 *   54:- Config hash: `edb81695973b81ab8f87f7ef9dde9d8c5b3d4c7dfbeb45f385547edd86ee86de`
 *
 *     A DUPLICATED build-identity block (lines 51-57 repeated lines 35-38) that
 *     published `edb81695…` as "Config hash", while line 141 of the SAME report
 *     labelled that hash "the tuning config only" and named
 *     `modelDefinitionHash` as the complete one. The report contradicted itself
 *     about which hash identifies the model.
 *
 *   $ grep -o "119 tests" FINAL_REPORT.md | head -1 ; grep "^# tests" audit/test-results.txt
 *   119 tests
 *   # tests 172
 *
 *     The gate table claimed "119 tests … 119/119" while the raw TAP summary in
 *     the same bundle reported 172.
 *
 *   $ grep -n "Memory across a 180-generation run" -A1 FINAL_REPORT.md
 *     A browser `performance.memory` delta published as memory-growth evidence,
 *     from a channel that was never probed for resolution.
 *
 * The report is now GENERATED by `tools/writeFinalReport.mjs`. These tests make
 * drift a build failure: every assertion compares the committed report against
 * the raw evidence, and several re-derive the number independently rather than
 * trusting either file.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { renderFinalReport, parseTap, selfAuditScans } from "../tools/writeFinalReport.mjs";
import { deriveGateStatuses, readExternalStatuses, deriveMilestoneStatus, GATES } from "../tools/gateRegistry.mjs";
import { MILESTONE_STATUS, HASH_LABELS } from "../src/config/milestoneStatus.js";
import { exactProbabilityGate } from "../tools/runFixture.mjs";
import { buildMeaningfulTraitGateEvidence } from "../tools/writeAuditEvidence.mjs";
import { currentModelConfig } from "../src/config/modelConfig.js";
import { ZONES } from "../src/config/zones.js";

const ROOT = resolve(join(dirname(fileURLToPath(import.meta.url)), ".."));
const read = (p) => readFileSync(join(ROOT, p), "utf8");
const readJson = (p) => JSON.parse(read(p));

const REPORT = read("FINAL_REPORT.md");
const TAP = parseTap(read("audit/test-results.txt"));
const FIXTURE = readJson("audit/fixture-results.json");
const CHAR = readJson("audit/characterization-results.json");
const OBS = readJson("audit/observer-invariance-hashes.json");
const REFS = readJson("audit/reference-file-hashes.json");

test("§26 — the committed report is exactly what the generator produces", () => {
  // The single strongest check: if anyone hand-edits the report, this fails.
  assert.equal(
    REPORT,
    renderFinalReport(),
    "FINAL_REPORT.md differs from `node tools/writeFinalReport.mjs` output — regenerate it " +
    "with `npm run report:final` instead of editing it by hand"
  );
});

test("§20 — the report's suite counts equal the raw TAP summary", () => {
  assert.ok(TAP.tests !== null, "the raw TAP summary must be parseable");
  assert.ok(TAP.pass !== null && TAP.fail !== null);

  // Every count must appear in the report...
  for (const [label, value] of [["tests", TAP.tests], ["pass", TAP.pass], ["fail", TAP.fail]]) {
    assert.match(
      REPORT,
      new RegExp(`\\| ${label} \\| ${value} \\|`),
      `the report must print the raw ${label} count ${value}`
    );
  }
  // ...and the gate-table row for the whole suite must state the SAME outcome. The
  // generator prints one canonical shape for that row,
  //
  //   | 1 | Full test suite | §20 | **PASS** — 299/299, 0 failing |
  //   | 1 | Full test suite | §20 | **FAIL** — 297/299, 2 failing |
  //
  // so both branches below match that shape and check the numbers in it. (Revision 5:
  // the failing branch previously matched `**FAIL** — N of M failing`, the wording of
  // the revision-3 example quoted in §9b rather than the wording this generator emits,
  // so the branch could not fire. It fired for the first time on a genuinely failing
  // run and was wrong; the numbers, not the prose, are what must agree.)
  const suiteRow = /\| Full test suite \| §20 \|[^|]*\| \*\*(PASS|FAIL)\*\* — (\d+)\/(\d+), (\d+) failing \|/;
  const row = REPORT.match(suiteRow);
  assert.ok(row, "the report must carry a Full test suite gate row with the raw counts");
  const [, verdict, rowPass, rowTests, rowFail] = row;
  assert.equal(Number(rowPass), TAP.pass, `the report claims ${rowPass} passing, the runner reported ${TAP.pass}`);
  assert.equal(Number(rowTests), TAP.tests, `the report claims ${rowTests} tests, the runner reported ${TAP.tests}`);
  assert.equal(Number(rowFail), TAP.fail, `the report claims ${rowFail} failing, the runner reported ${TAP.fail}`);
  assert.equal(
    verdict,
    TAP.fail === 0 ? "PASS" : "FAIL",
    TAP.fail === 0
      ? "a green run must not print a failing summary"
      : "a failing run must be reported as FAIL, not hidden"
  );

  // The reproduction section restates the same run and must not disagree with it.
  assert.match(
    REPORT,
    new RegExp(`\\| full test suite from clean \\| ${TAP.pass}/${TAP.tests}, ${TAP.fail} failures \\|`),
    "the reproduction table must restate the same counts"
  );

  // Wall-clock duration must NOT be reproduced: it differs on every run, so
  // printing it would make this comparison unsatisfiable by construction.
  assert.ok(
    !/^\| duration \|/m.test(REPORT),
    "the report must not print the run duration — it is nondeterministic and would " +
    "make the report and the results file permanently disagree"
  );
  // No stale count from an earlier revision may be ASSERTED. Quoting one inside an
  // explicit withdrawal is required, not forbidden — §9b names the revision-3
  // "119 tests … 119/119" claim precisely so a reader cannot carry it forward.
  for (const stale of [119, 122, 148, 172]) {
    if (stale === TAP.tests) continue;
    const pattern = new RegExp(`${stale}\\s*/\\s*${stale}`);
    const lines = REPORT.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (!pattern.test(lines[i])) continue;
      const context = lines.slice(Math.max(0, i - 6), i + 4).join(" ");
      assert.match(
        context,
        /[Ww]ithdrawn|[Rr]evision[- ][123]|stale|retired/,
        `the report asserts the stale suite count ${stale}/${stale} outside a withdrawal:\n  ${lines[i].trim()}`
      );
    }
  }
});

test("§9/§18 — modelDefinitionHash is the principal identity and the subset hash is labelled nonauthoritative", () => {
  assert.ok(
    REPORT.includes(`\`${HASH_LABELS.authoritative}\`** (authoritative)`),
    "the complete-model hash must be presented as authoritative"
  );
  assert.ok(
    REPORT.includes(`\`${HASH_LABELS.nonauthoritative}\` (**NONAUTHORITATIVE**)`),
    "the tuning-only subset hash must be explicitly labelled nonauthoritative"
  );
  assert.ok(REPORT.includes(CHAR.modelDefinitionHash), "the authoritative hash value must be printed");
  assert.ok(REPORT.includes(CHAR.tuningConfigHash), "the subset hash value must be printed, labelled");

  // The subset hash must never be presented as "the" config hash again.
  assert.ok(
    !/^\s*[-|]\s*Config hash:/m.test(REPORT),
    'no line may publish a bare "Config hash:" — the report distinguishes the two hashes'
  );
  // Exactly one build-identity block. Revision 3 had two.
  const identityBlocks = [...REPORT.matchAll(/### Build identity/g)].length;
  assert.equal(identityBlocks, 1, "the report must contain exactly one build-identity block");
  const configLines = [...REPORT.matchAll(/^\| Configuration \| /gm)].length;
  assert.equal(configLines, 1, "the configuration must be stated exactly once");

  // Evidence files must agree with each other on both hashes.
  assert.equal(FIXTURE.modelDefinitionHash, CHAR.modelDefinitionHash, "evidence files disagree on the model hash");
  assert.equal(FIXTURE.tuningConfigHash, CHAR.tuningConfigHash, "evidence files disagree on the subset hash");
  assert.notEqual(CHAR.modelDefinitionHash, CHAR.tuningConfigHash, "the two hashes must be distinguishable");
});

test("§26 — the report's status is the one the evidence derives", () => {
  // REVISION-6 CHANGE (M-2 / R6-J). This test used to compare the report against a
  // literal in `src/config/milestoneStatus.js`. That file no longer asserts a
  // status: it is derived from the published run plus the external inputs, so the
  // comparison is now between the report and a fresh derivation.
  const external = readExternalStatuses(read);
  const milestone = deriveMilestoneStatus(deriveGateStatuses(TAP, external), external);
  assert.ok(REPORT.includes(milestone.status), "the report must state the derived status");
  assert.ok(REPORT.includes("PROCESS WAIVER: PENDING PRINCIPAL DECISION"));
  assert.ok(REPORT.includes("IPAD TEST: PENDING_HUMAN_DEVICE_TEST"));
  assert.equal(milestone.mayDeclareCompletion, false);
  assert.ok(
    REPORT.includes("**Completion is NOT declared**"),
    "the report must not declare completion while mayDeclareCompletion is false"
  );
  // Every blocker the derivation found must be printed, not summarised away.
  for (const b of milestone.blockers) {
    assert.ok(REPORT.includes(`- ${b}`), `the report must print the blocker "${b}"`);
  }
  // Forbidden statuses may appear only inside an explicit withdrawal.
  for (const forbidden of MILESTONE_STATUS.forbiddenStatuses) {
    for (const line of REPORT.split("\n")) {
      if (!line.includes(forbidden)) continue;
      assert.match(
        line,
        /withdraw|must not|not reinstated|was false|revision 1|revision 2/i,
        `the report presents ${forbidden} as a current status:\n  ${line.trim()}`
      );
    }
  }
});

test("§19.3/§19.4 — fixture numbers in the report match the evidence AND a fresh computation", () => {
  // The report's §19.4 figures must be the evidence's figures.
  assert.match(REPORT, new RegExp(`\\*\\*${FIXTURE.successCounts.canopy} / ${FIXTURE.gates.seedCount}\\*\\*`));
  assert.match(REPORT, new RegExp(`\\*\\*${FIXTURE.successCounts.shoreline} / ${FIXTURE.gates.seedCount}\\*\\*`));
  assert.ok(REPORT.includes(FIXTURE.medians.canopyLow.toFixed(4)));
  assert.ok(REPORT.includes(FIXTURE.medians.shorelineHigh.toFixed(4)));
  assert.ok(REPORT.includes(String(FIXTURE.focalContributionExtinctionCount)));

  // The §19.3 gate must be present as evidence, not prose, and must reproduce.
  assert.ok(FIXTURE.exactProbabilityGate, "the §19.3 gate must be emitted into the evidence file");
  const fresh = exactProbabilityGate(currentModelConfig);
  for (const k of ["canopyLow", "canopyHigh", "canopyDelta", "shorelineLow", "shorelineHigh", "shorelineDelta"]) {
    assert.equal(
      FIXTURE.exactProbabilityGate[k],
      fresh[k],
      `${k} in the evidence file does not reproduce from the production survival path`
    );
  }
  assert.ok(REPORT.includes(fresh.canopyDelta.toFixed(6)), "the report must print the measured canopy delta");
  assert.ok(REPORT.includes(fresh.shorelineDelta.toFixed(6)), "the report must print the measured shoreline delta");
  assert.equal(fresh.allPass, true);
});

test("§9 — every trait delta in the report reproduces from the production path", () => {
  const evidence = readJson("audit/meaningful-trait-gate.json");
  const fresh = buildMeaningfulTraitGateEvidence();
  assert.equal(evidence.meaningful.length, fresh.meaningful.length);
  for (let i = 0; i < fresh.meaningful.length; i++) {
    const e = evidence.meaningful[i];
    const f = fresh.meaningful[i];
    assert.equal(e.trait, f.trait);
    for (const z of ZONES) {
      assert.equal(e.deltaByZone[z], f.deltaByZone[z], `${e.trait}/${z} does not reproduce`);
      assert.ok(
        REPORT.includes(f.deltaByZone[z].toFixed(6)),
        `the report must print the measured delta for ${f.trait}/${z}`
      );
    }
  }
  for (const n of fresh.neutral) {
    assert.equal(n.maxAbsoluteDelta, 0, `${n.trait} must be exactly neutral`);
  }
  assert.equal(evidence.allMeaningfulPass, true);
  assert.equal(evidence.allNeutralExactlyZero, true);
  assert.equal(evidence.probe.fixtureGenomeMatches, true, "the §9 probe must use the fixture's frozen genome");
});

test("§21.4 — guardrail figures and the named limitation match the raw batch", () => {
  const g = CHAR.guardrails;
  assert.ok(REPORT.includes(g.medianPopulation.toFixed(1)));
  for (let z = 0; z < ZONES.length; z++) {
    assert.ok(
      REPORT.includes(g.medianZoneLoads[z].toFixed(2)),
      `the report must print the measured ${ZONES[z]} median load`
    );
  }
  assert.ok(REPORT.includes(g.medianConcentration.toFixed(4)));
  assert.ok(REPORT.includes(`${(g.extinctionRate * 100).toFixed(2)}%`));
  assert.ok(REPORT.includes(`all ${g.concentrationIncludedSeedCount} non-extinct seeds`));

  // The named limitation must be re-derived from the per-seed records, and must
  // agree with what CHARACTERIZATION.md prints.
  const nonExtinct = CHAR.seeds.filter((s) => !s.extinct);
  const shorelineZeroBin = nonExtinct.filter((s) => s.zoneBinCounts[2] === 0).length;
  assert.ok(shorelineZeroBin > 0, "the limitation must be a real measurement, not a placeholder");
  assert.match(
    REPORT,
    new RegExp(`zero in ${shorelineZeroBin} of ${CHAR.declaredSeedRange.endInclusive} seeds`),
    `the report must state the measured count ${shorelineZeroBin}`
  );
  const characterization = read("CHARACTERIZATION.md");
  assert.ok(
    characterization.includes(`${shorelineZeroBin} of ${nonExtinct.length}`),
    "CHARACTERIZATION.md must state the same count as FINAL_REPORT.md"
  );
  // Medians must agree between the two reports, to the digits both print.
  for (let z = 0; z < ZONES.length; z++) {
    const printed = CHAR.guardrails.medianZoneLoads[z].toFixed(2);
    assert.ok(characterization.includes(printed), `CHARACTERIZATION.md must print ${printed}`);
  }
});

test("§22 — desktop figures in the report match the desktop JSON exactly", () => {
  if (!existsSync(join(ROOT, "audit", "desktop-measurements.json"))) {
    assert.fail("audit/desktop-measurements.json is required evidence");
  }
  const d = readJson("audit/desktop-measurements.json");
  assert.ok(REPORT.includes(d.browser.version), "the report must print the measured browser version");
  assert.ok(REPORT.includes(String(d.normalMode.frameCount)));
  assert.ok(REPORT.includes(String(d.renderStressMode.frameCount)));
  assert.ok(REPORT.includes(d.normalMode.medianFrameTimeMs.toFixed(2)));
  assert.ok(REPORT.includes(d.renderStressMode.p95FrameTimeMs.toFixed(2)));
  assert.ok(REPORT.includes(String(d.normalMode.populationAfterAdvance)));

  // Generation semantics must be stated, and consistent.
  assert.match(
    REPORT,
    new RegExp(`\\*\\*${d.generationSemantics.finalStateGeneration}\\*\\* with \\*\\*${d.normalMode.populationAfterAdvance}\\*\\* living`),
    "the report must tie the population to an explicit final generation"
  );
  // The ambiguous revision-3 field name must not be a live key anywhere. The
  // report is allowed to NAME it while explaining the defect — that mention is
  // the record — so the rule is about use, not about the English text.
  const deskText = read("audit/desktop-measurements.json");
  assert.ok(
    !deskText.includes("populationAfter180Generations"),
    "the ambiguous field name must not appear in the raw desktop evidence"
  );
  const reportLines = REPORT.split("\n");
  for (let i = 0; i < reportLines.length; i++) {
    if (!reportLines[i].includes("populationAfter180Generations")) continue;
    // Judge the surrounding context, not the single line: a withdrawal can put the
    // marker in its section heading or the following sentence.
    const context = reportLines.slice(Math.max(0, i - 6), i + 4).join(" ");
    assert.match(
      context,
      /[Rr]evision[- ]3|ambiguity|retired|[Ww]ithdrawn/,
      `the report mentions populationAfter180Generations without marking it as the revision-3 name:\n  ${reportLines[i].trim()}`
    );
  }

  // Memory: revision-5 shape (R5-5). Two separately named results, and the report
  // must never present the Node figure as the §22 Canvas measure.
  const cm = d.desktopCanvasMemory;
  const nh = d.nodeSimulationHeap;
  assert.ok(cm && nh, "both memory results must be present");
  assert.ok(
    REPORT.includes(`#### \`DESKTOP_CANVAS_MEMORY\` — the §22 subject: **${cm.status}**`),
    "the report must state the Canvas measure's status under its own heading"
  );
  assert.ok(
    REPORT.includes("`NODE_SIMULATION_HEAP` — a separate diagnostic, NOT the §22 subject"),
    "the Node heap must be marked as a separate diagnostic"
  );
  assert.ok(
    !/authoritative channel.*process\.memoryUsage/i.test(REPORT),
    "the report must not call a Node channel authoritative for the Canvas measure"
  );
  if (cm.status === "UNVERIFIED") {
    assert.ok(
      REPORT.includes(`DESKTOP_CANVAS_MEMORY: ${cm.status}`),
      "an unverified Canvas measure must be printed as UNVERIFIED"
    );
    assert.equal(cm.deltaBytes, null);
    // No numeric growth figure may be offered for the unmeasured subject.
    assert.ok(
      !/DESKTOP_CANVAS_MEMORY[\s\S]{0,400}?delta [\d,]+ bytes/.test(REPORT),
      "no numeric delta may accompany an UNVERIFIED Canvas result"
    );
  }
  // The revision-4 merged field must be gone from the raw evidence.
  assert.equal(d.memoryAcrossAdvance, undefined, "the merged revision-4 memory field must not exist");
  // The desktop run must not be presented as satisfying the iPad gate.
  assert.equal(d.windowComparison.satisfiesIpadGateWindows, false);
  assert.ok(REPORT.includes("Satisfies the iPad gate's windows: false"));
  assert.ok(REPORT.includes("PENDING_HUMAN_DEVICE_TEST"));
});

test("§21.6 — the report gives the traversal claim to the isolated worlds", () => {
  const edge = readJson("audit/edge-only-traversal-results.json");
  assert.ok(REPORT.includes("**Authoritative evidence: the isolated edge-only worlds only.**"));
  for (const key of ["canopyOnly", "shorelineOnly"]) {
    const e = edge[key];
    assert.ok(
      REPORT.includes(`**${e.seedsReaching} of ${e.ofSeeds}**`),
      `the report must print the measured ${key} count`
    );
  }
  const authIdx = REPORT.indexOf("## 6b. §21.6 adjacency traversal");
  const suppIdx = REPORT.indexOf("### Supporting measure only — mixed-world single-band ancestry (NOT the §21.6 claim)");
  assert.ok(authIdx >= 0 && suppIdx > authIdx, "the supporting measure must follow, and disclaim, the real one");
  const L = CHAR.lifecycle;
  const mixC = L.additionalMixedWorldCanopyAncestryReachesShoreline;
  assert.ok(
    REPORT.includes(`${mixC.seedsReaching} of ${mixC.ofSeeds}`),
    "the mixed-world figure must be the measured one"
  );
});

test("§27 — observer-invariance and reference-file claims match their evidence", () => {
  assert.equal(OBS.allStrategiesByteIdentical, true);
  assert.equal(OBS.mismatches.length, 0);
  assert.ok(
    REPORT.includes(`**${OBS.strategies.length} strategies × ${OBS.generations + 1} generations`),
    "the report must print the measured strategy and generation counts"
  );
  assert.equal(REFS.allUnchanged, true);
  assert.ok(REPORT.includes(`${REFS.allUnchanged} (${REFS.files.length} files)`));
});

test("§27 — the manifest's evidence-file list matches what actually exists", () => {
  const manifest = read("AUDIT_PACKAGE_MANIFEST.md");
  const required = [
    "audit/test-results.txt",
    "audit/fixture-results.json",
    "audit/characterization-results.json",
    "audit/characterization-results-config1.json",
    "audit/observer-invariance-hashes.json",
    "audit/reference-file-hashes.json",
    "audit/edge-only-traversal-results.json",
    "audit/desktop-measurements.json",
    "audit/meaningful-trait-gate.json",
  ];
  for (const rel of required) {
    assert.ok(existsSync(join(ROOT, rel)), `${rel} must exist`);
    assert.ok(manifest.includes(rel), `AUDIT_PACKAGE_MANIFEST.md must list ${rel}`);
  }
  // Every audit file the manifest names must exist — no phantom evidence.
  for (const m of manifest.matchAll(/`(audit\/[A-Za-z0-9._-]+)`/g)) {
    assert.ok(existsSync(join(ROOT, m[1])), `the manifest names ${m[1]}, which does not exist`);
  }
  // Every audit file that exists must be named — no undisclosed evidence.
  // `audit/test-results.txt.partial` is excluded: it exists only while the suite is
  // running and is renamed over the published file on exit (tools/runTests.mjs).
  // Without this exclusion the check failed against the very run executing it,
  // which says nothing about whether the manifest is honest.
  for (const name of readdirSync(join(ROOT, "audit"))) {
    if (name.endsWith(".partial")) continue;
    assert.ok(
      manifest.includes(`audit/${name}`),
      `audit/${name} exists but is not listed in AUDIT_PACKAGE_MANIFEST.md`
    );
  }
});

test("§27 — every published command is documented in the manifest's clean-run section", () => {
  // §23/§27 require the auditor to be able to re-run the evidence from the bundle.
  // Revision 5 added four evidence commands (`audit:environment`,
  // `audit:runtime-matrix`, `audit:tree-integrity`, `manifest:paths`) and the first
  // draft of the manifest documented none of them, so three raw evidence files had
  // no published way to regenerate them. This keeps the two in step in both
  // directions.
  const manifest = read("AUDIT_PACKAGE_MANIFEST.md");
  const start = manifest.indexOf("## 2. Exact clean-run commands");
  const end = manifest.indexOf("## 3. Required hashes");
  assert.ok(start >= 0 && end > start, "the manifest must carry a clean-run command section");
  const section = manifest.slice(start, end);

  const pkg = readJson("package.json");
  for (const [name, cmd] of Object.entries(pkg.scripts)) {
    // A script is documented either by its npm alias or by the tool it runs — the
    // manifest uses `node tools/…` form for the long evidence generators.
    const tool = cmd.match(/tools\/[A-Za-z0-9._-]+\.mjs/);
    const documented =
      section.includes(`npm run ${name}`) ||
      (name === "test" && section.includes("npm test")) ||
      (tool !== null && section.includes(tool[0]));
    assert.ok(
      documented,
      `package.json declares the "${name}" script but §2 of the manifest documents no way to run it`
    );
  }

  // ...and no phantom command: every npm alias the manifest names must exist.
  for (const m of section.matchAll(/npm run ([A-Za-z0-9:_-]+)/g)) {
    assert.ok(
      m[1] in pkg.scripts,
      `the manifest documents \`npm run ${m[1]}\`, which package.json does not declare`
    );
  }
  // ...and every tool the manifest names must ship.
  for (const m of section.matchAll(/tools\/[A-Za-z0-9._-]+\.mjs/g)) {
    assert.ok(existsSync(join(ROOT, m[0])), `the manifest names ${m[0]}, which does not exist`);
  }
});

test("§26 — the report is marked as generated so it is not hand-edited", () => {
  assert.ok(REPORT.startsWith("# LINEAGE Milestone 1 — Final Implementation Report"));
  assert.ok(REPORT.includes("> **GENERATED FILE.**"));
  assert.ok(REPORT.includes("tools/writeFinalReport.mjs"));
  const pkg = readJson("package.json");
  assert.equal(pkg.scripts["report:final"], "node tools/writeFinalReport.mjs");
});

test("§24 Stage G — the self-audit scans report the live tree, and are clean", () => {
  // The scans run at report-generation time and their output is printed verbatim,
  // so this asserts the live tree is clean and the report says so.
  //
  // Proving the scanner has TEETH now lives in `test/test-tree-integrity.test.js`,
  // which plants violations into an isolated temporary copy. Revision 4 planted them
  // into `src/` while `node --test` ran files concurrently; a watcher caught the
  // production tree holding an import of a package that does not exist (BUG 8 /
  // R5-8). A test must not make the source tree transiently invalid for other
  // workers.
  const scan = selfAuditScans();
  assert.deepEqual(scan.unseededRandom, [], "no unseeded randomness may ship");
  assert.deepEqual(scan.observerImports, [], "biology must not import observer or debug modules");
  assert.deepEqual(scan.observerRngRefs, [], "observer modules must not touch the simulation RNG");
  assert.deepEqual(scan.bareImports, [], "src/ must have no runtime dependencies");

  // The report must print these results, not a remembered claim.
  assert.ok(REPORT.includes("Each scan below was executed by `tools/writeFinalReport.mjs`"));
  assert.ok(REPORT.includes("| unseeded-random search across `src/` and `tools/` | no occurrences |"));
});

// ---------------------------------------------------------------------------
// R5-7 / BUG 7 — failure injection: a failing test must turn ITS gate FAIL
// ---------------------------------------------------------------------------

/**
 * A synthetic, fully-green run in which every registry-declared test passed.
 *
 * The injection tests below must not depend on the COMMITTED run being green — that
 * made them fail during the tree-integrity rounds, when the committed results file
 * legitimately carried failures. Deriving the baseline from the registry makes each
 * injection a controlled experiment on the derivation logic itself, which is the
 * thing under test.
 */
function syntheticGreenRun() {
  const perTest = new Map();
  for (const g of GATES) for (const name of g.tests ?? []) perTest.set(name, true);
  return { tests: perTest.size, pass: perTest.size, fail: 0, perTest };
}

test("§20/§26 — injecting a failure into any gate category turns that gate FAIL, never PASS", () => {
  // Revision 4 derived only the full-suite row from tap.fail; every feature row was
  // a literal `**PASS**`, so changing the summary from 249/249 to 248/249 produced:
  //
  //   Full test suite: FAIL — 1 of 249 failing
  //   Birth immutability: PASS
  //   Canonical model identity: PASS
  //   every automated result reproducible from a clean run: met — 248/249 from clean
  //
  // Nothing is written to disk here: the derivation is a pure function of a parsed
  // run, so the injection happens in memory.
  const GREEN = syntheticGreenRun();
  const baseline = deriveGateStatuses(GREEN);

  // In a fully-green run every test-evidenced gate must read PASS; that is the
  // precondition the injections then falsify one at a time.
  const testGates = baseline.gates.filter((g) => g.evidence === "tests" && g.status === "PASS");
  assert.ok(testGates.length >= 8, `expected many evidenced gates, found ${testGates.length}`);

  for (const gate of testGates) {
    const victim = gate.mappedTests[0];
    assert.ok(victim, `${gate.id} must declare at least one evidencing test`);

    // Flip exactly that one test to failing.
    const injected = {
      ...GREEN,
      pass: GREEN.pass - 1,
      fail: 1,
      perTest: new Map([...GREEN.perTest, [victim, false]]),
    };
    const after = deriveGateStatuses(injected);
    const row = after.gates.find((g) => g.id === gate.id);

    assert.equal(row.status, "FAIL", `${gate.id} must become FAIL when "${victim}" fails`);
    assert.ok(row.failedTests.includes(victim), `${gate.id} must name the failing test`);
    // The suite row must also fail.
    assert.equal(after.gates.find((g) => g.id === "fullSuite").status, "FAIL");
    // And the §28 completion claim must not remain met.
    assert.equal(
      after.summary.everyAutomatedResultReproducible,
      "NOT met",
      `${gate.id}: completion must not read met while a gate fails`
    );
    // No gate may be reported PASS on the strength of a run that failed
    // unattributably; here the failure IS attributed, so other gates keep their
    // evidenced status — but the failing one must never be PASS.
    assert.notEqual(row.status, "PASS");
  }
});

test("§20/§26 — an UNATTRIBUTABLE failure degrades every other gate to UNVERIFIED", () => {
  // A failing test that no gate claims means the run does not evidence the other
  // gates either. Revision 4 would have kept every hardcoded PASS.
  const GREEN = syntheticGreenRun();
  const injected = {
    ...GREEN,
    pass: GREEN.pass,
    fail: 1,
    perTest: new Map([...GREEN.perTest, ["some test no gate declares", false]]),
  };
  const after = deriveGateStatuses(injected);
  assert.deepEqual(after.unattributedFailures, ["some test no gate declares"]);
  const derivedGates = after.gates.filter((g) => g.evidence === "tests");
  assert.ok(derivedGates.length > 0);
  for (const g of derivedGates) {
    assert.notEqual(g.status, "PASS", `${g.id} must not read PASS while a failure is unattributed`);
  }
  assert.equal(after.summary.everyAutomatedResultReproducible, "NOT met");
});

test("§20/§26 — a gate whose evidencing test did not run reads UNVERIFIED, never PASS", () => {
  const GREEN = syntheticGreenRun();
  const baseline = deriveGateStatuses(GREEN);
  const gate = baseline.gates.find((g) => g.evidence === "tests" && g.status === "PASS");
  const missing = gate.mappedTests[0];
  const perTest = new Map(GREEN.perTest);
  perTest.delete(missing);
  const after = deriveGateStatuses({ ...GREEN, perTest });
  const row = after.gates.find((g) => g.id === gate.id);
  assert.equal(row.status, "UNVERIFIED", `${gate.id} must be UNVERIFIED when its test did not run`);
  assert.ok(row.missingTests.includes(missing));
  assert.equal(after.summary.everyAutomatedResultReproducible, "NOT met");
});

test("§20/§26 — externally determined gates can never read PASS", () => {
  // Checked against a fully-green run: even then they must not pass.
  // Revision-6: external statuses are READ from their named inputs, so the shipped
  // inputs are supplied here rather than being baked into the registry.
  const d = deriveGateStatuses(syntheticGreenRun(), readExternalStatuses(read));
  const external = d.gates.filter((g) => g.evidence === "external");
  assert.ok(external.length >= 3, "the iPad gate, Stage A order and Canvas memory are external");
  for (const g of external) {
    assert.notEqual(g.status, "PASS", `${g.id} must never read PASS`);
    assert.equal(g.machineVerified, false, `${g.id} must not be presented as machine-verified`);
    assert.ok(g.evidenceSource, `${g.id} must name where its status was read from`);
  }
  const byId = Object.fromEntries(external.map((g) => [g.id, g.status]));
  assert.equal(byId.ipadGate, "PENDING_HUMAN_DEVICE_TEST");
  assert.equal(byId.desktopCanvasMemory, "UNVERIFIED");
  assert.match(byId.stageAOrder, /VIOLATED/);
});

test("§20/§26 — the committed gate summary matches the report's table", () => {
  const summary = readJson("audit/gate-summary.json");
  const derived = deriveGateStatuses(TAP, readExternalStatuses(read));
  assert.equal(summary.gates.length, derived.gates.length);
  for (let i = 0; i < derived.gates.length; i++) {
    assert.equal(summary.gates[i].id, derived.gates[i].id);
    assert.equal(
      summary.gates[i].status,
      derived.gates[i].status,
      `${derived.gates[i].id}: committed summary disagrees with a fresh derivation`
    );
    // ...and the report row must carry that same status.
    const marker = derived.gates[i].status === "PASS" ? "**PASS**" : `**${derived.gates[i].status}**`;
    const row = REPORT.split("\n").find((l) => l.includes(`| ${derived.gates[i].label} |`));
    assert.ok(row, `the report must contain a row for ${derived.gates[i].id}`);
    assert.ok(
      row.includes(marker),
      `${derived.gates[i].id}: report row does not carry ${marker}\n  ${row.trim()}`
    );
  }
  assert.deepEqual(summary.summary, derived.summary);
});
