// @ts-check
/**
 * Regenerate the "Every included path" inventory in AUDIT_PACKAGE_MANIFEST.md
 * from the actual bundle contents (contract §27).
 *
 * Revision-4 repair. The inventory was hand-maintained, so it silently went stale
 * as files were added. A manifest that omits a shipped file, or names a file that
 * is not shipped, is a false statement about what the auditor received.
 *
 * The walk applies exactly the §27 exclusion categories and nothing else:
 * `.git/`, `node_modules/`, OS metadata, editor metadata, replaceable caches.
 *
 * Usage: node tools/writeManifestPaths.mjs [--check]
 *   --check exits non-zero if the manifest is stale instead of rewriting it.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join, resolve, relative, sep } from "node:path";

const ROOT = resolve(join(dirname(fileURLToPath(import.meta.url)), ".."));

const BEGIN = "<!-- BEGIN GENERATED PATH INVENTORY -->";
const END = "<!-- END GENERATED PATH INVENTORY -->";

/** Directory names excluded wholesale — exactly the §27 categories. */
const EXCLUDED_DIRS = new Set([".git", "node_modules", ".vscode", ".idea", "__pycache__", ".cache"]);
/** File names excluded — OS and editor metadata. */
const EXCLUDED_FILES = new Set([".DS_Store", "Thumbs.db", "desktop.ini"]);
/** Suffixes excluded — temporary editor files. */
const EXCLUDED_SUFFIXES = [
  ".swp", ".swo", "~", ".pyc", ".tmp",
  // `audit/test-results.txt.partial` exists only while the suite is running; it is
  // renamed over the published file on exit (see tools/runTests.mjs). Including it
  // would make the inventory depend on whether a run happens to be in flight.
  ".partial",
];

/** @param {string} name */
function isExcludedFile(name) {
  if (EXCLUDED_FILES.has(name)) return true;
  return EXCLUDED_SUFFIXES.some((s) => name.endsWith(s));
}

/**
 * Every shipped path, POSIX-separated and sorted.
 * @returns {string[]}
 */
export function bundledPaths(root = ROOT) {
  /** @type {string[]} */
  const found = [];
  /** @param {string} dir */
  const walk = (dir) => {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      const st = statSync(full);
      if (st.isDirectory()) {
        if (EXCLUDED_DIRS.has(name)) continue;
        walk(full);
      } else if (!isExcludedFile(name)) {
        found.push(relative(root, full).split(sep).join("/"));
      }
    }
  };
  walk(root);
  return found.sort();
}

/**
 * The inventory block, ready to splice into the manifest.
 * @param {string[]} paths
 */
export function renderInventory(paths) {
  const lines = [
    BEGIN,
    "",
    `Generated by \`node tools/writeManifestPaths.mjs\` from the bundle itself.`,
    `\`node tools/writeManifestPaths.mjs --check\` fails if this list has gone stale, and`,
    "`test/manifest-inventory.test.js` runs that check in the build-blocking suite.",
    "",
    `**${paths.length} files.**`,
    "",
    ...paths.map((p) => `- \`${p}\``),
    "",
    END,
  ];
  return lines.join("\n");
}

/**
 * Splice the generated block into the manifest text.
 * @param {string} text
 * @param {string} block
 */
export function spliceInventory(text, block) {
  const b = text.indexOf(BEGIN);
  const e = text.indexOf(END);
  if (b >= 0 && e > b) {
    return text.slice(0, b) + block + text.slice(e + END.length);
  }
  // First run: replace the hand-maintained list under the section heading.
  const heading = "## 7. Every included path";
  const hi = text.indexOf(heading);
  if (hi < 0) throw new Error('AUDIT_PACKAGE_MANIFEST.md has no "## 7. Every included path" section');
  const after = text.indexOf("\n---", hi);
  const end = after < 0 ? text.length : after;
  return text.slice(0, hi + heading.length) + "\n\n" + block + "\n" + text.slice(end);
}

const isMain =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const manifestPath = join(ROOT, "AUDIT_PACKAGE_MANIFEST.md");
  const text = readFileSync(manifestPath, "utf8");
  const paths = bundledPaths();
  const next = spliceInventory(text, renderInventory(paths));
  if (process.argv.includes("--check")) {
    if (next !== text) {
      console.error("AUDIT_PACKAGE_MANIFEST.md path inventory is STALE. Run: node tools/writeManifestPaths.mjs");
      process.exitCode = 1;
    } else {
      console.log(`manifest path inventory is current (${paths.length} files)`);
    }
  } else {
    writeFileSync(manifestPath, next);
    console.log(`manifest path inventory regenerated: ${paths.length} files`);
  }
}
